// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addItemToCart = `-- name: AddItemToCart :exec
INSERT INTO cart_items (cart_id, product_id, qty, price_snapshot)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, product_id) DO UPDATE SET
    qty = cart_items.qty + EXCLUDED.qty,
    price_snapshot = EXCLUDED.price_snapshot
`

type AddItemToCartParams struct {
	CartID        pgtype.UUID    `json:"cart_id"`
	ProductID     pgtype.UUID    `json:"product_id"`
	Qty           int32          `json:"qty"`
	PriceSnapshot pgtype.Numeric `json:"price_snapshot"`
}

func (q *Queries) AddItemToCart(ctx context.Context, arg AddItemToCartParams) error {
	_, err := q.db.Exec(ctx, addItemToCart,
		arg.CartID,
		arg.ProductID,
		arg.Qty,
		arg.PriceSnapshot,
	)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items 
WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (guest_token) 
VALUES ($1) 
RETURNING id, user_id, guest_token, status, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, guestToken pgtype.Text) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, guestToken)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestToken,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByGuestToken = `-- name: GetCartByGuestToken :one
SELECT id, user_id, guest_token, status, created_at, updated_at FROM carts 
WHERE guest_token = $1 AND status = 'active' 
LIMIT 1
`

func (q *Queries) GetCartByGuestToken(ctx context.Context, guestToken pgtype.Text) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByGuestToken, guestToken)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestToken,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT 
    ci.id, ci.cart_id, ci.product_id, ci.qty, ci.price_snapshot,
    p.name as product_name,
    p.slug as product_slug,
    p.sku as product_sku,
    pp.price as current_price,
    pp.currency
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
LEFT JOIN product_prices pp ON p.id = pp.product_id
WHERE ci.cart_id = $1
`

type GetCartItemsRow struct {
	ID            pgtype.UUID    `json:"id"`
	CartID        pgtype.UUID    `json:"cart_id"`
	ProductID     pgtype.UUID    `json:"product_id"`
	Qty           int32          `json:"qty"`
	PriceSnapshot pgtype.Numeric `json:"price_snapshot"`
	ProductName   string         `json:"product_name"`
	ProductSlug   string         `json:"product_slug"`
	ProductSku    string         `json:"product_sku"`
	CurrentPrice  pgtype.Numeric `json:"current_price"`
	Currency      pgtype.Text    `json:"currency"`
}

func (q *Queries) GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Qty,
			&i.PriceSnapshot,
			&i.ProductName,
			&i.ProductSlug,
			&i.ProductSku,
			&i.CurrentPrice,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items 
WHERE cart_id = $1 AND product_id = $2
`

func (q *Queries) RemoveCartItem(ctx context.Context, cartID pgtype.UUID, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeCartItem, cartID, productID)
	return err
}

const updateCartItemQty = `-- name: UpdateCartItemQty :exec
UPDATE cart_items 
SET qty = $3 
WHERE cart_id = $1 AND product_id = $2
`

func (q *Queries) UpdateCartItemQty(ctx context.Context, cartID pgtype.UUID, productID pgtype.UUID, qty int32) error {
	_, err := q.db.Exec(ctx, updateCartItemQty, cartID, productID, qty)
	return err
}
