// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name, created_at FROM categories
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT
    p.id, p.slug, p.sku, p.name, p.short_description, p.description, p.composition, p.indications, p.contraindications, p.usage, p.manufacturer, p.is_active, p.created_at, p.updated_at,
    pp.price,
    pp.old_price,
    pp.currency,
    i.qty_available
FROM products p
         LEFT JOIN product_prices pp ON p.id = pp.product_id
         LEFT JOIN inventory i ON p.id = i.product_id
WHERE p.slug = $1 AND p.is_active = true
    LIMIT 1
`

type GetProductBySlugRow struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	Sku               string             `json:"sku"`
	Name              string             `json:"name"`
	ShortDescription  pgtype.Text        `json:"short_description"`
	Description       pgtype.Text        `json:"description"`
	Composition       pgtype.Text        `json:"composition"`
	Indications       pgtype.Text        `json:"indications"`
	Contraindications pgtype.Text        `json:"contraindications"`
	Usage             pgtype.Text        `json:"usage"`
	Manufacturer      pgtype.Text        `json:"manufacturer"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Price             pgtype.Numeric     `json:"price"`
	OldPrice          pgtype.Numeric     `json:"old_price"`
	Currency          pgtype.Text        `json:"currency"`
	QtyAvailable      pgtype.Int4        `json:"qty_available"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Sku,
		&i.Name,
		&i.ShortDescription,
		&i.Description,
		&i.Composition,
		&i.Indications,
		&i.Contraindications,
		&i.Usage,
		&i.Manufacturer,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Price,
		&i.OldPrice,
		&i.Currency,
		&i.QtyAvailable,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, created_at FROM categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id, p.slug, p.sku, p.name, p.short_description, p.description, p.composition, p.indications, p.contraindications, p.usage, p.manufacturer, p.is_active, p.created_at, p.updated_at,
    pp.price,
    pp.old_price,
    pp.currency,
    i.qty_available
FROM products p
         LEFT JOIN product_prices pp ON p.id = pp.product_id
         LEFT JOIN inventory i ON p.id = i.product_id
WHERE p.is_active = true
ORDER BY p.created_at DESC
`

type ListProductsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	Sku               string             `json:"sku"`
	Name              string             `json:"name"`
	ShortDescription  pgtype.Text        `json:"short_description"`
	Description       pgtype.Text        `json:"description"`
	Composition       pgtype.Text        `json:"composition"`
	Indications       pgtype.Text        `json:"indications"`
	Contraindications pgtype.Text        `json:"contraindications"`
	Usage             pgtype.Text        `json:"usage"`
	Manufacturer      pgtype.Text        `json:"manufacturer"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Price             pgtype.Numeric     `json:"price"`
	OldPrice          pgtype.Numeric     `json:"old_price"`
	Currency          pgtype.Text        `json:"currency"`
	QtyAvailable      pgtype.Int4        `json:"qty_available"`
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Sku,
			&i.Name,
			&i.ShortDescription,
			&i.Description,
			&i.Composition,
			&i.Indications,
			&i.Contraindications,
			&i.Usage,
			&i.Manufacturer,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Price,
			&i.OldPrice,
			&i.Currency,
			&i.QtyAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT
    p.id, p.slug, p.sku, p.name, p.short_description, p.description, p.composition, p.indications, p.contraindications, p.usage, p.manufacturer, p.is_active, p.created_at, p.updated_at,
    pp.price,
    pp.old_price,
    pp.currency
FROM products p
         JOIN product_categories pc ON p.id = pc.product_id
         LEFT JOIN product_prices pp ON p.id = pp.product_id
WHERE pc.category_id = $1 AND p.is_active = true
ORDER BY p.created_at DESC
`

type ListProductsByCategoryRow struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	Sku               string             `json:"sku"`
	Name              string             `json:"name"`
	ShortDescription  pgtype.Text        `json:"short_description"`
	Description       pgtype.Text        `json:"description"`
	Composition       pgtype.Text        `json:"composition"`
	Indications       pgtype.Text        `json:"indications"`
	Contraindications pgtype.Text        `json:"contraindications"`
	Usage             pgtype.Text        `json:"usage"`
	Manufacturer      pgtype.Text        `json:"manufacturer"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Price             pgtype.Numeric     `json:"price"`
	OldPrice          pgtype.Numeric     `json:"old_price"`
	Currency          pgtype.Text        `json:"currency"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID pgtype.UUID) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Sku,
			&i.Name,
			&i.ShortDescription,
			&i.Description,
			&i.Composition,
			&i.Indications,
			&i.Contraindications,
			&i.Usage,
			&i.Manufacturer,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Price,
			&i.OldPrice,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
