// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	GuestToken pgtype.Text        `json:"guest_token"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CartItem struct {
	ID            pgtype.UUID    `json:"id"`
	CartID        pgtype.UUID    `json:"cart_id"`
	ProductID     pgtype.UUID    `json:"product_id"`
	Qty           int32          `json:"qty"`
	PriceSnapshot pgtype.Numeric `json:"price_snapshot"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Inventory struct {
	ProductID    pgtype.UUID        `json:"product_id"`
	QtyAvailable int32              `json:"qty_available"`
	QtyReserved  int32              `json:"qty_reserved"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                  pgtype.UUID        `json:"id"`
	OrderNumber         string             `json:"order_number"`
	UserID              pgtype.UUID        `json:"user_id"`
	Status              string             `json:"status"`
	TotalAmount         pgtype.Numeric     `json:"total_amount"`
	Currency            string             `json:"currency"`
	DeliveryMethod      string             `json:"delivery_method"`
	DeliveryPrice       pgtype.Numeric     `json:"delivery_price"`
	DeliveryAddressJson []byte             `json:"delivery_address_json"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID           pgtype.UUID    `json:"id"`
	OrderID      pgtype.UUID    `json:"order_id"`
	ProductID    pgtype.UUID    `json:"product_id"`
	NameSnapshot string         `json:"name_snapshot"`
	SkuSnapshot  string         `json:"sku_snapshot"`
	Price        pgtype.Numeric `json:"price"`
	Qty          int32          `json:"qty"`
	LineTotal    pgtype.Numeric `json:"line_total"`
}

type PaymentAttempt struct {
	ID                pgtype.UUID        `json:"id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	Provider          string             `json:"provider"`
	Status            string             `json:"status"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          string             `json:"currency"`
	ProviderPaymentID pgtype.Text        `json:"provider_payment_id"`
	ProviderPayload   []byte             `json:"provider_payload"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	Sku               string             `json:"sku"`
	Name              string             `json:"name"`
	ShortDescription  pgtype.Text        `json:"short_description"`
	Description       pgtype.Text        `json:"description"`
	Composition       pgtype.Text        `json:"composition"`
	Indications       pgtype.Text        `json:"indications"`
	Contraindications pgtype.Text        `json:"contraindications"`
	Usage             pgtype.Text        `json:"usage"`
	Manufacturer      pgtype.Text        `json:"manufacturer"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProductCategory struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type ProductMedium struct {
	ID        pgtype.UUID `json:"id"`
	ProductID pgtype.UUID `json:"product_id"`
	Type      string      `json:"type"`
	Url       string      `json:"url"`
	SortOrder int32       `json:"sort_order"`
}

type ProductPrice struct {
	ProductID pgtype.UUID        `json:"product_id"`
	Currency  string             `json:"currency"`
	Price     pgtype.Numeric     `json:"price"`
	OldPrice  pgtype.Numeric     `json:"old_price"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Phone        pgtype.Text        `json:"phone"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	FullName     string             `json:"full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
